const Config = {
  mode: "light",
  highlightList: [
    //* Write the words you want to emphasize in the description in the About You section using lowercase letters.
    "javascript",
    "reactjs",
    "nextjs",
    "mongodb",
    "html",
    "css",
    "tailwindcss",
    "bootstrap",
    "materialui",
    "nextui",
    "typescript",
    "redux",
    "redux-toolkit",
    "e-commerce",
    "mantin",
    "scss",
  ],
  information: {
    name: "Halit Uzan",
    email: "halit.uzan@gmail.com",
    phone: "+905301142548",
    country: "Türkiye",
    city: "İstanbul",
    degree: "Junior",
    freelance: true,
    remote: true,
    birthDay: "28 Şubat 1992",
    title: "Full-Stack Web Developer",
  },
  social: [
    {
      id: "github",
      name: "Github",
      icon: "mdi:github",
      url: "https://github.com/halituzan",
    },
    {
      id: "twitter",
      name: "Twitter",
      icon: "mdi:twitter",
      url: "https://x.com/uzandev",
    },
    {
      id: "linkedin",
      name: "LinkedIn",
      icon: "mdi:linkedin",
      url: "https://www.linkedin.com/in/halituzan/",
    },
    {
      id: "stackoverflow",
      name: "StackoverFlow",
      icon: "mdi:stackoverflow",
      url: "https://stackoverflow.com/users/12782922/halit-uzan",
    },
    // {
    //   id: "codewars",
    //   name: "Codewars",
    //   icon: "cib:codewars",
    //   url: "https://www.codewars.com/users/halituzan",
    // },
  ],
};
export default Config;
